stages:
  split:
    cmd: python src/data/split.py
    deps:
    - src/data/split.py
    - data/raw_data/raw.csv
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/y_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_test.csv

  noramlize:
    cmd: python src/data/normalize.py
    deps:
    - src/data/normalize.py
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    outs:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test_scaled.csv


  gridsearch:
    cmd: python src/models/grid_seach.py
    deps:
    - src/models/grid_seach.py
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    outs:
    - models/best_decision_tree_model.pkl
  
  train:
    cmd: python src/models/train.py 
    deps:
    - src/models/train.py
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/X_test.csv
    - models/best_decision_tree_model.pkl
    
    outs:
    - models/trained_decision_tree_model.pkl

  evaluate:
    cmd: python src/models/evaluation.py
    deps:
    - src/models/evaluation.py
    - models/trained_decision_tree_model.pkl
    - data/processed_data/y_test.csv
    - data/processed_data/X_test.csv
    - data/processed_data/X_test_scaled.csv

    outs:
    - metrics/scores.json
    - data/predictions.csv